version: '2'
services:
  instagramfollower-batch:
    image: registry.hub.docker.com/socialmonitoring20/instagram_scrapper
  socialnetworkmonitoring-app:
    image: registry.hub.docker.com/socialmonitoring20/socialnetworkmonitoring
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=portainer
    ports:
      - 9922:8000
  social-database:
    image: 'postgres:latest'
    expose:
      - 5432
    environment:
      POSTGRES_USER: root_soci@l_mo_user
      POSTGRES_PASSWORD: root_soci@l_mo_p@5sWord
      POSTGRES_DB: social-monitoring-database
    volumes:
      - ./db-data/:/var/lib/postgresql/data/


