version: '2'
services:
  seaevent-app:
    image: registry.hub.docker.com/yassineramzi/sea_event
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mariadb://seaevent-mariadb:3306/seaevent
    ports:
      - 8080:8080
  seaevent-mariadb:
    extends:
      file: mariadb.yml
      service: seaevent-mariadb
  keycloak:
    extends:
      file: keycloak.yml
      service: keycloak


