name: Docker image build

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, develop]
  pull_request:
    branches: [ master, develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [14.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up Maven
        uses: s4u/setup-maven-action@v1.2.1
        with:
          java-version: 11
          maven-version: 3.6.3
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Set up NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run:  |
          npm install -g @angular/cli@11.2.4
          cd src/main/resources/front
          npm ci
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build application Backend
        run:  |
          mvn clean compile jib:build -Dmode=portainer
